sources:
  - href: https://developer.chrome.com/static/blog/feed.xml
  - href: https://webkit.org/feed/atom/
  - href: https://hacks.mozilla.org/feed/
  - href: https://blogs.windows.com/msedgedev/feed/
  - href: https://developer.apple.com/news/rss/news.rss
